name: Build Python

on:
    push:
      branches:
        - "3.13"
    pull_request:
      branches:
        - "3.13"

jobs:
  build-windows:
    name: Build Python Fork (Windows)
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Check if python is installed before installed dependencies
      run: python --version

    - name: Install dependencies
      run: |
        choco install -y visualstudio2022buildtools visualstudio2022-workload-vctools
        choco install -y nasm

    - name: Configure environment
      run: |
        setx PATH "%PATH%;C:\\Program Files\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.x.x\\bin\\Hostx64\\x64"

    - name: Build Python
      shell: cmd
      run: |
        cd PCbuild
        build.bat -c Release

    - name: Upload binaries
      uses: actions/upload-artifact@v3
      with:
        name: python-fork-static-windows
        path: PCbuild\\amd64\\Release\\*
