name: Build Python Static

on:
  push:
    branches:
      - "3.13"
  pull_request:
    branches:
      - "3.13"

jobs:
  build-windows:
    name: Build Python Static (Windows)
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Check if python is installed before installing dependencies
      run: python --version

    - name: Install dependencies
      run: |
        choco install -y visualstudio2022buildtools visualstudio2022-workload-vctools
        choco install -y nasm

    - name: Configure environment
      run: |
        setx PATH "%PATH%;C:/Program Files/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.x.x/bin/Hostx64/x64"

    - name: Modify build.bat for static linking (PowerShell)
      shell: pwsh
      run: |
        # Replace -DLL with -MT for static linking
        (Get-Content "PCbuild/build.bat") -replace "-DLL", "-MT" | Set-Content "PCbuild/build.bat"
          
        # Remove the -shared flag
        (Get-Content "PCbuild/build.bat") -replace "-shared", "" | Set-Content "PCbuild/build.bat"
          
        # Replace /MD with /MT to use the static C runtime
        (Get-Content "PCbuild/build.bat") -replace "/MD", "/MT" | Set-Content "PCbuild/build.bat"

    - name: Build Python (Static)
      shell: cmd
      run: |
        cd PCbuild
        build.bat -c Release

    - name: Upload binaries
      uses: actions/upload-artifact@v3
      with:
        name: python-fork-static-windows
        path: PCbuild/amd64/python*.*
